version: "3"

services:
    url-shortener:
        build: ./url-shortener-backend
        ports:
            - "9007:8080"
        container_name: url-shortener-java
        networks:
            - dokploy-network
        environment:
            MONGODB_HOST: "management-urlshortenerjavadb-v680aj"
            MONGODB_PORT: 27017
            # MONGODB_PASSWORD: "<???>"
            # MONGODB_USERNAME: "<???>"
networks:
  dokploy-network:
    external: true
