version: "3"

services:
    url-shortener:
        build: ./url-shortener-backend
        ports:
            - "9007:8080"
        container_name: url-shortener-java
        networks:
            - dokploy-network
        environment:
            MONGODB_HOST: "management-urlshortenerjavadb-v680aj"
            MONGODB_PORT: 27017
            MONGODB_PASSWORD: ${MONGODB_PASSWORD}
            MONGODB_USERNAME: ${MONGODB_USERNAME}
    url-shortener-frontend:
        build: ./url-shortener-frontend
        ports:
            - "8080:80"
        container_name: url-shortener-frontend
        networks:
            - dokploy-network
networks:
  dokploy-network:
    external: true
